eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
    metadata-map:
      management.context-path: ${management.context-path}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

spring:
  rabbitmq:
    host: rabbitmq
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"

management:
  security:
    enabled: false

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/current