eureka:
  instance:
    hostname: registry
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

spring:
  rabbitmq:
    host: localhost
  sleuth:
    sampler:
      percentage: 1