server:
  context-path: /uaa
  port: 5000

eureka:
  instance:
    metadata-map:
      management.context-path: ${server.context-path}
      health.path: ${server.context-path}/health

spring:
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true