server:
  context-path: /uaa
  port: 5000

eureka:
  instance:
    health-check-url-path: ${server.context-path}/health
    status-page-url-path: ${server.context-path}/info
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${server.context-path}

spring:
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

security:
  user:
    name: user
    password: password